name: Build for MIPSLE

on:
  workflow_dispatch:
    inputs:
      target_arch:
        description: 'Target Architecture'
        required: true
        default: 'mipsle'
        type: choice
        options:
          - mipsle
          - arm
          - amd64

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # 所有 actions 更新到最新版

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=${{ github.event.inputs.target_arch }} \
          GOMIPS=softfloat \
          go build -o filebrowser-${{ github.event.inputs.target_arch }}

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: filebrowser-${{ github.event.inputs.target_arch }}
          path: filebrowser-${{ github.event.inputs.target_arch }}
