name: Build for MIPSLE

on:
  workflow_dispatch:  # 手动触发
    inputs:
      target_arch:
        description: 'Target Architecture (e.g., mipsle, arm)'
        required: true
        default: 'mipsle'
        type: choice
        options:
          - mipsle
          - arm
          - amd64

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'

      - name: Build Binary
        run: |
          GOOS=linux GOARCH=${{ github.event.inputs.target_arch }} \
          GOMIPS=softfloat \
          go build -o filebrowser-${{ github.event.inputs.target_arch }}
          file filebrowser-${{ github.event.inputs.target_arch }}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: filebrowser-${{ github.event.inputs.target_arch }}
          path: filebrowser-${{ github.event.inputs.target_arch }}
